### PR TITLE
ZEP-303 rebrand docs

### PR DESCRIPTION
**Pull request by corroded**
Rebranded API docs. Changed some colours with @sharmanat0r 

## BEFORE

image

## AFTER

image

P.S. I still think we need higher contrast in the sub nav background. Calling for backup @paraokelly-split

### CODE REVIEW

**Comment by trev** [comment]
Great stuff @corroded, just one thing. Can we shrink the logo again by 30%?

**Comment by paraokelly-zepto** [comment]
Screen Shot 2021-08-30 at 3 04 35 pm
Wondering if you want the submenu colour to be either darker (0A0A0E), or lighter (55555C) To be a little more obvious to viewers.  (Both colours have a contrast >7 for white text).  Might make it easier to read. :)

**Comment by trev** [comment]
Thanks @paraokelly-split & @corroded. Whatever we do, let's make sure it's inline with branding colours so we don't end up with all these different shades of grey 😉. If the brand guidelines don't support the necessary contrasts, let's look creating a subset that's derived from the main colours for special use cases.

**Comment by corroded** [comment]
> Thanks @paraokelly-split & @corroded. Whatever we do, let's make sure it's inline with branding colours so we don't end up with all these different shades of grey 😉. If the brand guidelines don't support the necessary contrasts, let's look creating a subset that's derived from the main colours for special use cases.

@sharmanat0r and I derived it from the main colours. I'll park this for now but will revisit after the launch! I think @paraokelly-split also has some issues with the purple so we will have a chat and propose this to whoever owns brand/colour guidelines

**Comment by sharmanat0r** [comment]
Happy with it, we can tweak in post :)

**Review by sharmanat0r — APPROVED** [review]

**Pull request merged**
