### PR TITLE
SSL verification mode

### PR DESCRIPTION
**Pull request by zubin**
## Context

Currently our API docs suggest skipping host verification. This is not a good idea, particularly when dealing with money. 

## Change

- Change to `VERIFY_PEER`. 
- Fix a typo. 

## Discussion

Will this change get overwritten next time the docs are generated?

### CODE REVIEW

**Review by danieldraper — APPROVED** [review]
👍  Nice work.

I'm approving this based on the assumption you have confirmed `VERIFY_PEER` works against our API in sandbox and production?

**Comment by zubin** [comment]
> 👍 Nice work.
> 
> I'm approving this based on the assumption you have confirmed `VERIFY_PEER` works against our API in sandbox and production?

I hadn't, on the basis that there's no certificate warning when accessing those sites. 

Confirmed with `curl` (unless the SSL certs were valid, these would fail without `-k` option). 

```sh
$ curl -I https://api.sandbox.split.cash/check.json
HTTP/2 200

$ curl -I https://api.preprod.split.cash/check.json
HTTP/2 200
```

**Comment by zubin** [comment]
Looks like the `VERIFY_PEER` change will get clobbered. 

It's part of [httpsnippet](https://github.com/Kong/httpsnippet/search?q=VERIFY_NONE):

image

**Review by kieranjogrady — APPROVED** [review]

**Comment by zubin** [comment]
I'm not sure it's worth merging this, since these changes will get clobbered. We need to look at httpsnippet (see my previous comment) to see if/how this issue can be avoided there (hopefully configurable).

**Comment by igas** [comment]
@zubin did you open issue/pr in httpsnippet?

**Comment by zubin** [comment]
> @zubin did you open issue/pr in httpsnippet?

No, Ajay's been considering a different tool for API docs so I've paused this for now.

**Comment by zubin** [comment]
Closing, on the presumption that we're changing tools and therefore not worth the time investment.

**Pull request closed without merging**
